name = "workers-cache-assets-repro-with-assets"
main = "src/index.js"
compatibility_date = "2026-07-08"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[cache]
enabled = true
cross_version_cache = false

[exports.default]
type = "worker"

  [exports.default.cache]
  enabled = false

[exports.Cached]
type = "worker"

  [exports.Cached.cache]
  enabled = true
